
- op: replace
  path: /spec/template/spec/containers/0/image
  value: developementregistry.azurecr.io/devops-frontend   # change this to your docker registry

- op: add 
  path: /spec/template/spec/containers/0/envFrom
  value: 
    - configMapRef:
        name: env-configs-dev

- op: add 
  path: /spec/revisionHistoryLimit
  value: 2  