apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 



configMapGenerator:
- envs:
  - config.env # Contains configs environment var
  name: env-configs-dev
generatorOptions:
 disableNameSuffixHash: true