name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'kustomize/**'
env:
   REGISTRY_NAME: developementRegistry
   REGISTRY_DOMAIN: azurecr.io  # add your docker registry here 
   IMAGE_NAME: devops-frontend
   KUSTOMIZE_REPO: zohebk8s/github-argocd
   LOCAL_HOST_LINK: https://demo-be.zohebk8s.com/
   ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  replace-env-vars:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
           
      - name: Check Out Repo 
        uses: actions/checkout@v2
        

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: developementregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
          
      - name: Print first 10 characters of commit SHA
        run: echo "${{ github.sha }}"
        
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
            
      - name: Set up Docker Build
        run: | 
            docker build . -f ./src/Dockerfile -t developementregistry.azurecr.io/devops-frontend:${SHORT_SHA}
            
      - name: Push Docker image-dev
        run: docker push developementregistry.azurecr.io/devops-frontend:${SHORT_SHA}
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Kustomize repository
        uses: actions/checkout@v2
        with:
          repository: zohebk8s/github-argocd
          ref: main
          token: ${{ secrets.GITHUBTOKEN }}   
 
      - name: Setup kustomize 
        uses: imranismail/setup-kustomize@v1.3.0
        with:
          kustomize-version: 'v4.2.0'
          
          
      - name: Replace image tag
        run: |
          ls
          cd kustomize/overlays/dev
          kustomize edit set image developementregistry.azurecr.io/devops-frontend:${SHORT_SHA}
          git config --global user.email "ADD YOUR EMAIL USED IN YOUR GITHUB HERE"
          git config --global user.name "zohebk8s"
          git add .
          git commit -m "Replace image tag"
          git push
          
      - name: Commit changes config.env 
        run: |
          cd kustomize/overlays/dev/envs
          ls
          if [ -f config.env ] && grep -q "^LOCAL_HOST_LINK=${LOCAL_HOST_LINK}$" config.env; then
            echo "LOCAL_HOST_LINK value has not changed. Skipping commit."
          else
              rm config.env || true
              echo "LOCAL_HOST_LINK=${LOCAL_HOST_LINK}" >> config.env
              git add config.env
              git commit -m "Update LOCAL_HOST_LINK value to ${LOCAL_HOST_LINK}"
              git push
              echo "LOCAL_HOST_LINK value has changed successfully. Skipping commit."
            fi



            